App/urls.py
from App.models import Service
from . import views
from django.urls import path

app_name = 'App'

urlpatterns = [
    path('', views.HomeView, name = 'home'),
    path('create-head', views.CreateHead, name = 'head-create'),
    path('create-listen', views.CreateListen, name = 'listen-create'),
    path('select-service/<int:id>', views.SelectService, name = 'select-service'),
    path('details/', views.AllDetails, name = 'all-details'),

    path('api/service', views.service_details, name = 'service-details'),
    path('api/head', views.head_details, name = 'head-details'),
    path('api/listen', views.listen_details, name = 'listen-details'),
    path('api/led', views.led_details, name = 'led-details'),
    path('api/led-change', views.led_post, name = 'led-change'),
]

ExpoProj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('App.urls')),
]

App/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Service(models.Model):
    name = models.CharField(max_length = 25)
    created_at = models.DateTimeField(auto_now_add = True)
    time = models.DecimalField(max_digits = 25,decimal_places=3)
    icon = models.CharField(max_length=100, default = 'home')

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
    
    def __str__(self):
        return self.name
    
    def get_url(self):
        # return reverse()
        pass

class Listen(models.Model):
    listening_time = models.IntegerField(help_text='in seconds', default=7)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    time = models.DecimalField(max_digits = 25,decimal_places=3)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Listening Time'
        verbose_name_plural = 'Listening Time'

    def __str__(self):
        return str(self.listening_time)


class Head(models.Model):
    up_time = models.IntegerField(help_text='In seconds', default=10)
    down_time = models.IntegerField(help_text='In seconds', default=10)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now = True)
    time = models.DecimalField(max_digits = 25,decimal_places=3)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Head Setting'
        verbose_name = 'Head Settings'

    def __str__(self):
        return "{}".format("Head Settting "+str(self.id))

class SetService(models.Model):
    service_name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now = True)
    time = models.DecimalField(max_digits=30, decimal_places=3)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'SetService'
        verbose_name_plural = 'Set Services'

    def __str__(self):
        return self.service_name


class Led(models.Model):
    status  = models.BooleanField(default=True)
    time = models.DecimalField(max_digits=30, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'LED Setting'
        verbose_name_plural = 'LED Settings'

    def __str__(self):
        return str(self.status)

App/views.py
from typing import List, Set

from django.http import request
from App.serializers import HeadSerializer, ListenSerializer, SetServiceSerializer, LedSerializer
from django.shortcuts import render, redirect
from.models import Led, Service, Listen, Head, SetService, Led

from rest_framework.decorators import api_view
from rest_framework.response import Response
import time
from django.contrib import messages

# Create your views here.

def HomeView(request):
    qs  =  Service.objects.all()
    return render(request, 'App/index.html', {'qs':qs})

def AllDetails(request):
    service = SetService.objects.latest('pk')
    head = Head.objects.latest('pk')
    listen = Listen.objects.latest('pk')
    return render(request, 'App/detail.html', {'service':service, 'head':head, 'listen':listen})




def CreateHead(request):
    if request.method == "POST":
        
        up_time = request.POST['up_time']
        down_time = request.POST['down_time']
        obj = Head.objects.latest('pk')
        obj.up_time = up_time
        obj.down_time = down_time
        obj.time = time.time()
        obj.save()
        messages.info(request, 'Head settings updated succesfully')


        return redirect('App:home')
    return render(request, 'App/head.html')



def CreateListen(request):
    if request.method == "POST":
        
        listen_time = request.POST['listen_time']
        obj = Listen.objects.latest('pk')
        obj.listening_time = listen_time
        obj.time = time.time()
        obj.save()
        messages.info(request, 'Listening settings updated succesfully')

        return redirect('App:home')
    return render(request, 'App/listen.html')

def SelectService(request, id):
    obj = Service.objects.get(id = id)
    print(obj.name)

    set = SetService.objects.latest('pk')

    set.service_name = obj.name
    set.time = time.time()
    set.save()
    messages.info(request, set.service_name+' Conversation Service started succesfully')
    return redirect('App:home')







#######################    REST VIEWS     #######################
@api_view(['GET'])
def head_details(request):
    data = Head.objects.latest('pk')
    serializer = HeadSerializer(data, many = False)
    return Response(serializer.data)

    
@api_view(['GET'])
def listen_details(request):
    data = Listen.objects.latest('pk')
    serializer = ListenSerializer(data, many = False)
    return Response(serializer.data)

@api_view(['GET'])
def service_details(request):
    data = SetService.objects.latest('pk')
    serializer = SetServiceSerializer(data, many = False)
    return Response(serializer.data)

@api_view(['GET'])
def led_details(request):
    data = Led.objects.latest('pk')
    serializer = LedSerializer(data, many = False)
    return Response(serializer.data)

@api_view(['POST'])
def led_post(request):
    l = Led.objects.latest('pk')
    serializer = LedSerializer(instance = l, data = request.POST)

    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)

App/templates/App/detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="">
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link rel="stylesheet" href="{% static "izitoast/css/iziToast.min.css" %}">
<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
</head>
<body>


<!-- HEADER =============================-->
<header class="item header margin-top-0">
<div class="wrapper">
	<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
			<i class="fa fa-bars"></i>
			<span class="sr-only">Toggle navigation</span>
			</button>
			<a href="" class="navbar-brand brand"> VISTAN NEXTGEN </a>
		</div>
		<div id="navbar-collapse-02" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="propClone"><a href="{% url 'App:head-create' %}">Head</a></li>
				<li class="propClone"><a href="{% url 'App:listen-create' %}">Listening</a></li>
				<li class="propClone"><a href="{% url 'App:home' %}">Conversation</a></li>
				<li class="propClone"><a href="{% url 'App:all-details' %}">Default</a></li>
				
			</ul>
		</div>
	</div>
	</nav>

</div>
</header>



	
	<!-- LATEST ITEMS =============================-->
<section class="item content">
	<div class="container">
		<div class="underlined-title">
			<div class="editContent">
				<h1 class="text-center latestitems"></h1>
			</div>
			
		</div>
		<br><br>
		
	</div>
</div>
</section>





<!-- AREA =============================-->
<div class="item content">
	<div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                
                <table class="table">
            
                    <tbody>
                      <tr>
                        
                        <td>Conversation Type</td>
                        <b>
                            <td><b>{{service.service_name}} Conversation</b></td>
                            <td><a href="{% url 'App:home' %}">Edit</a></td>
                        </b>
                   
                      </tr>
                      <tr>
                        
                        <td>Head Up time</td>
                        <b>
                            <td><b>{{head.up_time}} </b>Secs</td>
                            <td><a href="{% url 'App:head-create' %}">Edit</a></td>

                        </b>
              
                      </tr>
                      <tr>
                        
                        <td>Head Down time</td>
                        <td><b>{{head.down_time}}</b> Secs</td>
                        <td><a href="{% url 'App:head-create' %}">Edit</a></td>

              
                      </tr>
                      <tr>
                        
                        <td>Listening time</td>
                        <td><b>{{listen.listening_time}} </b>Secs</td>
                        <td><a href="{% url 'App:listen-create' %}">Edit</a></td>

              
                      </tr>
                      
                    </tbody>
                  </table>

            </div>
            <div class="col-2"></div>


        
        </div>
    </div>
</div>




<!-- SCRIPTS =============================-->
<script src="{% static "js/jquery-.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/anim.js" %}"></script>
<script src="{% static "izitoast/js/iziToast.min.js" %}"></script>
<script>
//----HOVER CAPTION---//	  
jQuery(document).ready(function ($) {
	$('.fadeshop').hover(
		function(){
			$(this).find('.captionshop').fadeIn(150);
		},
		function(){
			$(this).find('.captionshop').fadeOut(150);
		}
	);
});
</script>


{% if messages%}
  <script>
        iziToast.show({
                        title: 'Yayy!',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'green'
                    });
  </script>
  {% endif %}
	
</body>
</html>

App/templates/App/head.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="">
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
</head>
<body>


<!-- HEADER =============================-->
<header class="item header margin-top-0">
<div class="wrapper">
	<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
			<i class="fa fa-bars"></i>
			<span class="sr-only">Toggle navigation</span>
			</button>
			<a href="" class="navbar-brand brand"> VISTAN NEXTGEN </a>
		</div>
		<div id="navbar-collapse-02" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="propClone"><a href="{% url 'App:head-create' %}">Head</a></li>
				<li class="propClone"><a href="{% url 'App:listen-create' %}">Listening</a></li>
				<li class="propClone"><a href="{% url 'App:home' %}">Conversation</a></li>
				<li class="propClone"><a href="{% url 'App:all-details' %}">Default</a></li>

				
			</ul>
		</div>
	</div>
	</nav>

</div>
</header>



	
	<!-- LATEST ITEMS =============================-->
<section class="item content">
	<div class="container">
		<div class="underlined-title">
			<div class="editContent">
				<h1 class="text-center latestitems"></h1>
			</div>
			
		</div>
		<br><br>
		
	</div>
</div>
</section>






	<div class="container">
    <!-- Default form subscription -->
        <form class="text-center border border-light p-5" method = "POST">{% csrf_token %}
            <p class="h4 mb-4">Choose the Head settings of Maira!</p><br>  

            <input type="number" 
                id="" 
                class="form-control mb-4" 
                placeholder="Enter head_up time in seconds"
                name = "up_time">
            <br>

            <input type="number" 
                id="" 
                class="form-control mb-4" 
                placeholder="Enter head_down time in seconds"
                name = "down_time">
            <br>             
            <button class="btn btn-success btn-block" type="submit">Submit</button>
        </form>	
	</div>





<!-- SCRIPTS =============================-->
<script src="{% static "js/jquery-.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/anim.js" %}"></script>
<script>
//----HOVER CAPTION---//	  
jQuery(document).ready(function ($) {
	$('.fadeshop').hover(
		function(){
			$(this).find('.captionshop').fadeIn(150);
		},
		function(){
			$(this).find('.captionshop').fadeOut(150);
		}
	);
});
</script>
	
</body>
</html>

App/templates/App/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="">
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link rel="stylesheet" href="{% static "izitoast/css/iziToast.min.css" %}">
<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
</head>
<body>


<!-- HEADER =============================-->
<header class="item header margin-top-0">
<div class="wrapper">
	<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
			<i class="fa fa-bars"></i>
			<span class="sr-only">Toggle navigation</span>
			</button>
			<a href="" class="navbar-brand brand"> VISTAN NEXTGEN </a>
		</div>
		<div id="navbar-collapse-02" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="propClone"><a href="{% url 'App:head-create' %}">Head</a></li>
				<li class="propClone"><a href="{% url 'App:listen-create' %}">Listening</a></li>
				<li class="propClone"><a href="{% url 'App:home' %}">Conversation</a></li>
				<li class="propClone"><a href="{% url 'App:all-details' %}">Default</a></li>
				
			</ul>
		</div>
	</div>
	</nav>

</div>
</header>



	
	<!-- LATEST ITEMS =============================-->
<section class="item content">
	<div class="container">
		<div class="underlined-title">
			<div class="editContent">
				<h1 class="text-center latestitems"></h1>
			</div>
			
		</div>
		<br><br>
		
	</div>
</div>
</section>





<!-- AREA =============================-->
<div class="item content">
	<div class="container">
		<div class="row">

			{% for i in qs%}
			<div class="col-md-4">
				<i class="fa {{i.icon}} infoareaicon"></i>
				<div class="infoareawrap" style=border-color:#95A5A6;>
					<h1 class="text-center subtitle">{{i.name}} Conversation</h1>
					
					<p class="text-center">
						 <a href="{% url 'App:select-service' i.id %}" class="btn btn-warning">SELECT</a>
					</p>
				</div>
			</div>

			{% endfor %}
			
		</div>
	</div>
</div>




<!-- SCRIPTS =============================-->
<script src="{% static "js/jquery-.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/anim.js" %}"></script>
<script src="{% static "izitoast/js/iziToast.min.js" %}"></script>
<script>
//----HOVER CAPTION---//	  
jQuery(document).ready(function ($) {
	$('.fadeshop').hover(
		function(){
			$(this).find('.captionshop').fadeIn(150);
		},
		function(){
			$(this).find('.captionshop').fadeOut(150);
		}
	);
});
</script>


{% if messages%}
  <script>
        iziToast.show({
                        title: 'Yayy!',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'green'
                    });
  </script>
  {% endif %}
	
</body>
</html>

App/templates/App/listen.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="">
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
</head>
<body>


<!-- HEADER =============================-->
<header class="item header margin-top-0">
<div class="wrapper">
	<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
			<i class="fa fa-bars"></i>
			<span class="sr-only">Toggle navigation</span>
			</button>
			<a href="" class="navbar-brand brand"> VISTAN NEXTGEN </a>
		</div>
		<div id="navbar-collapse-02" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="propClone"><a href="{% url 'App:head-create' %}">Head</a></li>
				<li class="propClone"><a href="{% url 'App:listen-create' %}">Listening</a></li>
				<li class="propClone"><a href="{% url 'App:home' %}">Conversation</a></li>
				<li class="propClone"><a href="{% url 'App:all-details' %}">Default</a></li>

				
			</ul>
		</div>
	</div>
	</nav>

</div>
</header>



	
	<!-- LATEST ITEMS =============================-->
<section class="item content">
	<div class="container">
		<div class="underlined-title">
			<div class="editContent">
				<h1 class="text-center latestitems"></h1>
			</div>
			
		</div>
		<br><br>
		
	</div>
</div>
</section>






	<div class="container">
    <!-- Default form subscription -->
        <form class="text-center border border-light p-5" method = "POST">
        {% csrf_token %}
            <p class="h4 mb-4">Choose the Listening settings of Maira!</p><br>  

            <input type="number" 
                id="" 
                class="form-control mb-4" 
                placeholder="Enter listening time in seconds"
                name = "listen_time">
            <br>

           
            <button class="btn btn-success btn-block" type="submit">Submit</button>
        </form>	
	</div>





<!-- SCRIPTS =============================-->
<script src="{% static "js/jquery-.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/anim.js" %}"></script>
<script>
//----HOVER CAPTION---//	  
jQuery(document).ready(function ($) {
	$('.fadeshop').hover(
		function(){
			$(this).find('.captionshop').fadeIn(150);
		},
		function(){
			$(this).find('.captionshop').fadeOut(150);
		}
	);
});
</script>
	
</body>
</html>